#!/bin/sh

# site is subject to change
site="https://1337x.wtf"

# replace whitespace with plus sign
query=$(echo "$1" | tr ' ' '+')

echo "Movie:" $query

movie=$(curl -s $site/search/$query/1/ | grep -Eo "torrent\/[0-9]+\/[a-zA-Z0-9?&%-]*\/" | head -n 1)

echo $movie

magnet=$(curl -s $site/$movie | grep -Eo "magnet:\?xt=urn:btih:[0-9A-Z]*" | head -n 1)

echo "Magnet Link:" $magnet

peerflix -k $magnet